name: todo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: 3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  provider: ^6.0.5
  flutter_hooks: ^0.20.1
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
